(define (problem caminhao_numerico) 
    (:domain caminhao_numerico) 
    (:objects ADoubleRef - refrigerated_truck 
                BDouble - truck depot 
                GV E BW - location) ;; Declare objects for integers, up to the largest quantity ;; that appears in the problem: 

    (:init (at ADoubleRef depot) 
            (at BDouble depot)
            (= (free_capacity ADoubleRef) 40)
            (= (free_capacity BDouble) 34)
            (= (demand_chilled_goods GV) 18)
            (= (demand_ambient_goods GV) 12)
            (= (demand_chilled_goods E) 7)
            (= (demand_ambient_goods E) 2)
            (= (demand_chilled_goods BW) 3)
            (= (demand_ambient_goods BW) 0)
            (=(distance depot GV) 573)
            (=(distance depot E) 896)
            (=(distance depot BW) 876)
            (=(distance GV depot) 573)
            (=(distance GV E) 372)
            (=(distance GV BW) 296)
            (=(distance E depot) 896)
            (=(distance E GV) 372)
            (=(distance E BW) 79)
            (=(distance BW depot) 876)
            (=(distance BW GV) 296)
            (=(distance BW E) 79)
            (=(per_km_cost ADoubleRef) 3.04)
            (=(per_km_cost BDouble) 2.59)
            (=(total-cost) 0)
    ) 
   (:goal (and (<= (demand_chilled_goods GV) 0)
               (<= (demand_ambient_goods GV) 0)
               (<= (demand_chilled_goods E) 0)
               (<= (demand_ambient_goods E) 0)
               (<= (demand_chilled_goods BW) 0)
               (<= (demand_ambient_goods BW) 0)
               (at ADoubleRef depot)
               (at BDouble depot))
   )
            
   (:metric minimize (total-cost))
   ; (:metric minimize
    ;    (+(demand_chilled_goods GV)
     ;       (+ (demand_ambient_goods GV)
      ;          (+ (demand_chilled_goods E)
       ;             (+ (demand_ambient_goods E)
        ;                (+ (demand_chilled_goods BW)
         ;                  (demand_ambient_goods BW)))))))
)